[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#C2410C"
backgroundColor = "#FFF7ED"
secondaryBackgroundColor = "#FFEDD5"
textColor = "#1C1917"
font = "sans serif"